### ISSUE TITLE
TachiyomiEH crashes without Google Chrome/Chrome.apk/com.android.chrome installed.

### ISSUE THREAD

**Issue by drogga3** [NerdNumber9/TachiyomiEH#118]
**App version:**
v8.4.5-EH
**Android version:**
Redmi Note 8/ginkgo
MIUI version: MIUI Global 11.0.3 | Stable
11.0.3.0 (PCOMIXM)
Android version: 9 PKQ1.190616.001
**Issue/Request:**
On device without /system/app/Chrome/Chrome.apk or com.android.chrome, TachiyomiEH crashes upon boot because hard dependancy on Google Chrome
**Steps to reproduce (if applicable)**
 1. Delete /system/app/Chrome/Chrome.apk
 2. Reboot device
 3. Launch TachiyomiEH
**Other details:**
Some may elect to remove Chrome or even worse, GApps on their device due to privacy concerns.
Issue status is unknown on upstream.

**Comment by AoiSeaghdha** [comment]
On LineageOS 16.0/Android 9 on a Note 9, both Tachiyomi and TachiyomiEH _(0.8.4 and 8.4.5)_ load perfectly fine for me without Chrome.apk and com.android.chrome.

Assuming you deleted Chrome after installing Tachiyomi, have you tried uninstalling and reinstalling Tachiyomi(EH) to see if may solve it? Altering system files can sometimes break currently installed apps due to the way they utilise cache/dalvik cache; I had an issue with an app force closing after I did a dirty update of my recovery, for instance.

My system uses microG as a replacement for GApps, but I don't think Google's PSF is likely to be the cause of anything here, as Tachiyomi isn't dependent on them so far as I'm aware.

EDIT: what is formatting

**Comment by drogga3** [comment]
Huh, interesting, never thought dalvik could work that way.

For now I'll close the issue, since this is no longer applictable to me.
