### ISSUE TITLE
HTTP 404 ERROR

### ISSUE THREAD

**Issue by ghost** [NerdNumber9/TachiyomiEH#19]
Current version: v6.8.2-EH
Issue: HTTP 404 ERROR for downloads from multiple galleries. Refreshed but issue is persistent.

**Comment by NerdNumber9** [comment]
1. What source does this occur on (E-Hentai/ExHentai/nhentai/etc..)?
2. Does it work if you:
    1. Remove the gallery from your favorites
    2. Clear the database and chapter cache in "Settings > Advanced"
    3. Add the gallery back to your favorites and download again?

**Comment by Skcyte** [comment]
Happened to me on Tsumino. Already tried what you mentioned but still getting 404. 

And it seems that the latest paging doesn't really match with the actual website. And Perveden latest paging is null pointer for me. 

Using the latest ver. 6.8.2

Edit: Tsumino somehow working again. But don't take full on my word. I assume is it because the captcha?

**Comment by NerdNumber9** [comment]
The 404 captcha issue should be fixed. Downloading stuff in the background may still be unstable, I will try to stabilize it over the next couple of releases but I can't promise anything here.
