### ISSUE TITLE
Very slow downloading 

### ISSUE THREAD

**Issue by lelouchsama9** [NerdNumber9/TachiyomiEH#20]
Slow with some sources  .. not using the full bandwidth ( used other apps and no problem with the speed ) ! 
Please add multi thread downloading
.......
http://hentairead.com
Please add this site if possible ! 
Thx

**Comment by NerdNumber9** [comment]
Which sources are you talking about and what do you mean by downloading? Do you mean downloading while reading or downloading in the background?

I will look into adding that source.

**Comment by lelouchsama9** [comment]
Almost all new sources have been added to the application as well as old sources
downloading in background ... For full speed while download process
( offline reading ) 
... 
Hentai cafe ( it takes ages to load covers ) 
N hentai 
Ex hentai 
E hentai 
Tusmino ( error 404 everywhere - loading Pages slowly regardless reading or downloading  ) 
Perv Eden ! 
.... 
All download in background slowly
Just wanted to notify you about adding multi thread download to the app  
And an option to change the quilty of downloded images like Eh hentai 
.... 
I know I'm asking a lot .. sorry for that .. you're such a great guy ! 
Many thx in advance !

**Comment by ichijoraku** [comment]
I also found an issue to that. I was using bluestack to download the manga coz I thought it can download 1 chapter in less than 1 min. My internet speed is 2-3/mbps.
I'm talking about kissmanga.

**Comment by NerdNumber9** [comment]
@lelouchsama9 
For hentai.cafe's slow covers: It's just their servers. It's super slow for me on the desktop as well.

Tsumino: They have some weird captcha system which causes 404s. There will be a semi-workaround in the next update to hopefully make the experience better.

Multi-threaded downloading was actually originally in the app but was removed after sites started banning people for using it (it stresses out the servers).

I want to hold off on adding hentairead.com for now because of this message on their home page: `We are back! Sorry for the inactivity in recent weeks, but we are working on a huge update that will completely change the site both aesthetically and functionally.`. Every time they change the site's design I have to rewrite the code in TachiyomiEH. I really don't like rewriting tons of code so to save some trouble, I will wait until the big update comes out.

@ichijoraku 
2 - 3/mbps is really slow. Like really, really, really slow. The lowest speed my ISP offers is 6 mbps... On top of that, Kissmanga is very slow in Tachiyomi because of Cloudflare. You probably want to report this issue to the original app (https://github.com/inorichi/tachiyomi), instead of here as they are the only ones who can fix this.

**Comment by T3mp3sT** [comment]
@NerdNumber9  What version did the multi-threading downloading exist?

**Comment by NerdNumber9** [comment]
@T3mp3sT It actually exists in the current version but it will be removed the next release. Go to `Settings > Downloads` and tap on `Simultaneous downloads`. There you can choose how many downloads you want to run at the same time.

**Comment by T3mp3sT** [comment]
@NerdNumber9 Does this also affect downloading of chapters when reading? AFAIK the chapters will wait for the previous chapter to download before starting the next one. I have a very slow internet.

**Comment by NerdNumber9** [comment]
This should be fixed in recent releases. Recent releases include multithreaded downloading in the reader.
