### ISSUE TITLE
Is this app still in development?

### ISSUE THREAD

**Issue by woeijiunn88** [NerdNumber9/TachiyomiEH#3]
Need to suggest some features and some problem need to fix. :smile:

**Comment by NerdNumber9** [comment]
Yes it is but sometimes I don't have that much time. What is the issue or feature you want fixed/implemented?

**Comment by woeijiunn88** [comment]
# **Bugs**
1. The _year_ in date of each manga doesn't show properly, every manga shows year 1970, but the _months_ and _days_ doesn't have problem.

# **Suggestions**
1. _Remove some unwanted section, such as **Library updates** and **Latest updates** in the drawer section._ 
> - For **library updates** section, it seems no needed for these manga website (because no manga chapter will be updated for every manga); 
> - And the **latest updates** section, it seems same functionality as the **Galleries** section (viewing the latest updates from the top).

2. _Remove **CHAPTERS** tab in the manga info page._
> - This function also not needed for those manga website, because only 1 chapter for every manga.
> - Seems chapters tab has been removed, download button can move to drop down menu on info page, and "Start reading" word can be placed at bottom, with material blue rectangle background. (P/S: Don't know how to pronounce in English, sorry, and these are JUST A SUGGESTION)
3. _Clickable tag_
> - Just the same function of NH website, tap on the tag and it will search based by tag.
4. _Change the name **DEFAULT** section tab to **UNCATEGORIZED** will be better._
5. _Add **ALL** button, to view all manga at the glance._

**That's all for my suggestions and bugs feedback, don't know is possible to do this or not, because I'm not developer.. 😝**
@NerdNumber9

**Comment by NerdNumber9** [comment]
@woeijiunn88 
1. Won't be done as some users read regular manga with the app and those screens are still useful
2. Won't be done as some users read regular manga with the app and those screens are still useful **but** I am considering how to remove that tab for NSFW sources only
3. I am considering doing this but it is _really, really_ hard.
4. "Uncategorized" seems very long and I will avoid changing this since I don't want to make too many necessary changes from the main app. Also I am lazy :(.
5. This is something that I will not do as they are working on it in the original app, you can watch this issue here: https://github.com/inorichi/tachiyomi/issues/943
