### ISSUE TITLE
Java error when accessing gallery sources

### ISSUE THREAD

**Issue by Yandols** [NerdNumber9/TachiyomiEH#4]
I just started using this today, really nice app with the addition of sources like nh and exh. But I'm pretty sure I just came across a problem that shouldn't happen.

Upon entering the app, checking on galleries from kissmanga, mangafox and mangahere _(I have these enabled because these are the sites I use)_ will always show the following error unless I open exh or nh first - `java.security.cert.CertPathValidatorException: Trust anchor for certification ...`

Exh and Nh always works for some reason and after switching to it and back to mangahere or any sources only then it works. It's pretty weird and I'm sure that's not the intended behaviour so just letting you know.

Version: TachiyomiEH v6.1.4
Phone: OnePlus 2 (not rooted) 
Android version: 6.0.1 (OxygenOS 3.6.0)

**Comment by NerdNumber9** [comment]
That's actually a problem with the main Tachiyomi app. It's been fixed in the code but the author has not released the next update (which will include the fixes) yet.

I will wait until the next release before I copy the fixes over to this app.

In case you are curious, the issues are outlined here:
https://github.com/inorichi/tachiyomi/issues/998
https://github.com/inorichi/tachiyomi/issues/999

**Comment by Yandols** [comment]
I knew there was something weird about it, good to know I wasn't the only one experiencing this problem. I should have also checked the main branch for issues since this was a fork.

**Comment by NerdNumber9** [comment]
Fixed in latest update and original app.
