### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by Zero777X** [NerdNumber9/TachiyomiEH#52]
I am attempting to restore a backup of mine, but it is unsuccessful. It appears that the titles relating to Hitomi.la are unable to be restored due to a JsonReader malfunction. Any suggestions to remove the titles from the backup would be helpful as well.

**Comment by Zero777X** [comment]
Error is com.google.stream.MalformedJsonException: Use JsonReader.setlenient(true) to accept malformed JSON at line 81 column 3 path $

It also only occurs with Hitomi.la and it stops backups containing Hitomi.la titles in their libraries.

**Comment by Krellow** [comment]
> Error is com.google.stream.MalformedJsonException: Use JsonReader.setlenient(true) to accept malformed JSON at line 81 column 3 path $
> 
> It also only occurs with Hitomi.la and it stops backups containing Hitomi.la titles in their libraries.

Did you find any solution to this? I'm having the same problem

**Comment by Scrxtchy** [comment]
Hitomi.la no longer works with the application as it should. You should make a backup of your library json file, and remove the hitomi.la entires from the record.

I'm assuming it's trying to fetch the covers or something, so it will break when attempting to do

**Comment by kadaikhan** [comment]
Can't restore backup in the v.8.2.0, it's stuck at 20%.

**Comment by Laurence02** [comment]
> Can't restore backup in the v.8.2.0, it's stuck at 20%.

I've had some restoring problems when moving from earlier versions, especially with stuff from the previous Hentai Cafe sources (which lead to errors in 8.2.0 because the source 6908 has been deprecated - as such, some JSON files are invalid). As much as it would be convenient if admin took a little lookie at this functionality - particularly at what happens when you load a backup from ilwaz's fork, I temporarily circumvented this through trial and error, by downgrading (for an example, to NerdNumber9's 7.4.4), and then importing the backup there. From there on, you can upgrade again to 8.2.0, and let the migrating functionality built in do its thing. It seems to work now!

**Comment by NerdNumber9** [comment]
Yeah, I totally forgot about old backups when I was changing the Hentai Cafe source, I'll throw in a fix for that in the next release. Sorry about that! I think there's a similar issue with backups with nhentai galleries in them as well.

**Comment by joseph619** [comment]
> Can't restore backup in the v.8.2.0, it's stuck at 20%.

Same here, backup stuck at 14%

![0-02-01-ea0982a6238cc220c208e799c5efebe60dc55987cf501c0d5a763e5609239710_fba0b0d3](https://user-images.githubusercontent.com/34897862/55682754-a8032e00-5905-11e9-863b-5c8345034aea.jpg)

**Comment by NerdNumber9** [comment]
Fixed in latest release.
