### ISSUE TITLE
Hentai Cafe removed

### ISSUE THREAD

**Issue by Suicide123** [NerdNumber9/TachiyomiEH#58]
**App version:** 8.2.0

**Android version:** 9 Pie

**Issue/Request:**
Why was it removed when it was still working? And if it's not possible to re-add it again is there any extensions that have Fakku content in it?

**Edit**
Welp I'm an idiot it's actually on the FoolSlide extension. I had to move all my files to local and move them back again for not reading shit.

**Comment by NerdNumber9** [comment]
Yeah, I did consider some people would miss the mention in the changelog because it was kinda vague: `Integrate HentaiCafe with the Tachiyomi extension`.

I'm going to be moving other sources to their Tachiyomi extensions over the next couple of releases so to make sure this doesn't happen again, I'll popup a window or something to warn users after they upgrade.
