### ISSUE TITLE
When is this ever a thing?? >:(

### ISSUE THREAD

**Issue by ghost** [NerdNumber9/TachiyomiEH#76]
So what now? This was never a thing. Why with the limitation??? https://ibb.co/8XK2r0q

**Comment by NerdNumber9** [comment]
This has been a thing for quite a while already. Also, I'm not the one who added that, it was E-Hentai/ExHentai who did it. It happens when you view too many images, too fast. If you want to reduce the chance of this happening, go to the `Settings` and make sure `Reader > Aggressively load pages` is off.
