### ISSUE TITLE
Exhentai thumbnails not loading

### ISSUE THREAD

**Issue by EvilMidnightLurker** [NerdNumber9/TachiyomiEH#78]
**App version:** 8.4.1-EH

**Android version:** 8.1.0

**Issue/Request:** As in the title. The thumbnails only load after clicking through. The Ilwaz fork already fixed this.

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by NerdNumber9** [comment]
I believe this happens because ilwaz's fork changed the settings on your ExHentai account causing TachiyomiEH to become confused.

Try logging out and logging back into ExHentai in TachiyomiEH. This will cause the app to re-check the settings in your account and change anything that might be causing problems.

I'm going to close this issue now but if my above advice does not help, please re-open the issue and I'll take another look at this.

**Comment by EvilMidnightLurker** [comment]
Nope, still the same.

**Comment by EvilMidnightLurker** [comment]
No, wait, it looks as though only the thumbnails that were originally affected still are, and everything newer or older than the ones seen when I opened it are working. Weird, but OK. :)
